![Logo](https://signup.na.leagueoflegends.com/theme/signup_new_theme/img/logo-lol-smaller.png)

# Abstract

The goal of our project is to develop an interactive visualization that is useful to everyone who plays League of Legends, the most popular PC video game in the world.

# About the Game

League of Legends is the most popular PC video game in the world. Statistics suggest 27m people play it every day with around 7.5m people play it simultaneously at its peak hours of popularity.

League of Legends is a MOBA, Multiplayer Online Battle Arena. You battle with your team to fight the enemy team to destroy towers guarding the enemy base, and then destroy said base. An average match of League of Legends lasts for about 20-50 minutes, though some matches may exceed this.

# About Decision Making

As I said before, League of Legends is actually a team game. And it's the team aspect of this game that requires a huge amount of strategy. No one carry can take on the entire team by himself without the aid of his teammates. Each team member, represented by a champion, brings something into the fray. Together, their combined might could be devastating or a complete disaster.

Generally, teams are matched against other teams of equal skill level. Winning and losing, though, isn’t a matter of luck. Strategy in choosing which players will best work to your advantage against the other team is what allows a team to dominate in a match. You gain an advantage when the skills of your players work synergistically and better together than the players of the other team.

There are approximately 126 champions that any person can play, after unlocking them with real money or in-game points, each with several abilities and all with their own stats. And given that there are 5 champions per team, you can imagine the huge number of possibilities of developing a synergistic team. Further, the choices for your team’s champions must also take into account the strengths, weaknesses, and synergies of the other team. This is where the depth of strategy of the game comes in.

# Gameplay

Before we **can** talk about how we will make a useful visualization, we **should** talk about the game's objectives.

* 5 vs. 5 team battle in a map where the objective is to destroy the opposing side’s base.
* Each player chooses a champion from the 120+ available champions. Each champion has different skills, strengths, and weaknesses.

While we **won't** go into detail about the strategies that are used at the highest tiers of competitive and professional gameplay, we **must** talk about the basic team roles at all tiers of gameplay.

The game map is divided into three lanes (top, middle, bottom) with 5 roles defined by these lanes.

![Game Map](http://rack.1.mshcdn.com/media/ZgkyMDE0LzA1LzIwL2QxL1N1bW1vbmVyc1JpLmUxMjRmLmpwZwpwCXRodW1iCTEyMDB4OTYwMD4/3ccb6445/e1c/Summoners-Rift.jpg)

* **Top**: Role for the champion in the top lane.
* **Mid**: Role for the champion in the middle lane.
* **Jungler**: No lane; spends time in the jungle and supports other lanes.
* **Marksman**: Role for one of the champions in the bottom lane. This player accumulates resources to become a damage threat later in the game.
* **Support**: Role for one of the champions in the bottom lane. This player helps the player in the Marksman role.

# Important Lecture Concepts

Week 1:

* Encourage the reader to think about substance rather than graphic design.
* Encourage the eye to compare different pieces of data.
* Reveal the data at several different levels of detail.

Week 2:

* Who are your users?
* What are their goals?
* What are the current gaps in understanding?
* What do users need to compare?
* What is the priority of tasks?
* Exploiting familiarity that our user base has to the game avatars

Week 3:

* Table = exhibit facts
* Graph = encode quantitative information using position and magnitude
* Chart = temporal data
* Maps = symbolic representations of physical geography

Week 4:

* MoSCoW prioritization (must, should, could, won't)

Week 6:

* differences: position, possibly hue
* similarities: proximity, connectedness, common fate 

Week 7:

* grouping (to highlight synergies vs. counters)
* contrast, concordance, conflict?

Week 8:

* Fitt's law (clickable areas)
* brushing and linking

Week 9:

* something to bring the user into the visualization (context, storytelling)
* something to bring the user back into the real world (discuss applications in the real world)

# Our Proposal


## Who are our users?

Our users are both new and old players of League of Legends.

## What are their goals?

There are different champions for each role. Each champion has a set of "counter" champions with strengths that counter the champion’s weaknesses. There are also synergies between skillsets that allow two or more champions to perform more effectively when they are on the same team.

Before the start of a game, each team chooses their champions based on a 1-2-2-2-2-1 alternating pick format. This alternating format allows for players to pick "counter" champions based on the champions the other team chooses as well as pick "complement" champions based on the champions your own team chooses.

Effective counterpicks give your team an advantage, and it is a very important part of gameplay, especially in professional-level play (TRIVIA: League of Legends is an [eSport](http://worlds.lolesports.com/en_US/worlds) and its players are granted [athlete visas](http://mashable.com/2013/07/12/league-of-legends-visa/)). Effective complement picks are also important.

Lower skilled teams that "outpick" a higher skilled team can flip the odds of a match.

## What is the task priority?

We propose to develop an interactive data visualization that allows players of all skill levels to find the champion that best synergizes with their current team, taking into account the opposing team's picks and the specific picks of their own team.

In other words, there is just one priority when making use of our interactive visualization: choosing an optimal champion.

## What do users need to compare?

So that we start with a high bar, there are already websites that visualize the data effectively such as [LoL King](http://www.lolking.net/charts), but these visualizations only consider your role as countering someone in the same lane or as synergizing with someone in the same lane.

# Our Data Set

Riot (the company behind League of Legends) has an API that allows us to parse historical game data with detailed information.

https://developer.riotgames.com/

Our exploratory data set contains a snapshot of the data returned by the `match` API and strictly includes the champions and roles for the winning and losing teams.

https://developer.riotgames.com/api/methods#!/1027/3483

In [ ]:
import sqlite3
import numpy as np
import pandas as pd

In [ ]:
con = sqlite3.connect("lol.db")

pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", con)

        name
0  summoners
1    matches
2  champions

# Task 1: Team Structure Anomalies

As noted in our introduction, our main data sets of interest are `champions` and `matches`.

In [ ]:
champions = pd.read_sql_query("SELECT * from champions", con)
champions.head(5)

   championId         key     name
0          62  MonkeyKing   Wukong
1          24         Jax      Jax
2          35       Shaco    Shaco
3          19     Warwick  Warwick
4          76     Nidalee  Nidalee

In [ ]:
matches = pd.read_sql_query("SELECT * from matches", con)
matches.head(5)

      matchId                 winTeam               lossTeam
0  1704136684    S1 C42 J254 T57 M161   M84 S412 J59 T69 C67
1  1704137311    J56 C429 S53 M34 T39   C119 T92 M69 S44 J59
2  1704138453  T92 M105 C104 J35 S201  S412 J80 C18 T38 M103
3  1704139519     S89 M38 C22 J80 T57  S16 T14 C104 M105 J62
4  1704145183    T62 J77 S412 C42 M61    M7 M24 J59 C104 T39

To start off our analysis, do you notice anything unusual in the above data set? Probably not. If we highlighted the anomaly with color, you might pause and ask, "What's different about that game?" but the answer would not be immediately obvious.

In [ ]:
roles = {'T': 'top', 'J': 'jungle', 'M': 'mid', 'C': 'carry', 'S': 'support'}

def expand_roles(team):
    return [(roles[member[0]], int(member[1:])) for member in team.split(' ')]

def extract_roles(prefix, team):
    team_roles = { prefix + '.' + role : [] for role in roles.itervalues() }

    for item in expand_roles(team):
        team_roles[prefix + '.' + item[0]].append(item[1])

    return team_roles

def extract_teams(row):
    teams = {}
    teams.update(extract_roles('win', row[2]))
    teams.update(extract_roles('loss', row[3]))
    return teams

In [ ]:
members_expanded = pd.DataFrame([
    extract_teams(row) for row in matches.itertuples()
])
members_expanded.head(5)

,loss.carry,loss.jungle,loss.mid,loss.support,loss.top,win.carry,win.jungle,win.mid,win.support,win.top
0,[67],[59],[84],[412],[69],[42],[254],[161],[1],[57]
1,[119],[59],[69],[44],[92],[429],[56],[34],[53],[39]
2,[18],[80],[103],[412],[38],[104],[35],[105],[201],[92]
3,[104],[62],[105],[16],[14],[22],[80],[38],[89],[57]
4,[104],[59],"[7, 24]",[],[39],[42],[77],[61],[412],[62]

So while we call out the five different roles, in this data set, it's clear that not everyone uses standard tactics, and some teams in the data set drop roles and double up on others.

# Task 2: Champion Win/Loss Ratios

We start with LoL King's [Highest Win Rate Champions](http://www.lolking.net/charts?region=all&type=champion-winrate&range=weekly&map=sr&queue=1x1&league=ranked) and [Lowest Win Rate Champions](http://www.lolking.net/charts?region=all&type=champion-loserate&range=weekly&map=sr&queue=1x1&league=ranked), which present the top 10 and bottom 10 champions, respectively. While useful, one can't help but wonder... what if the champion that a user enjoys playing most is in the other 30? How would we be able to augment the existing data visualizations help guide them in their gameplay?

In [ ]:
wins = pd.DataFrame([item + (1,) for row in matches.itertuples() for item in expand_roles(row[2])], columns = ['role', 'championId', 'win'])
losses = pd.DataFrame([item + (0,) for row in matches.itertuples() for item in expand_roles(row[3])], columns = ['role', 'championId', 'win'])

In [ ]:
wins_losses = pd.concat([wins, losses])

In [ ]:
champion_wins_losses = wins_losses.merge(champions).groupby(['name'])
champion_wins_losses = champion_wins_losses.aggregate({'win': [np.mean, np.sum]})
champion_wins_losses = champion_wins_losses.sort(columns = [('win', 'mean')], ascending = False)
champion_wins_losses

                   win
                  mean    sum
name
Nunu          0.545584   3435
Riven         0.539282   6775
Ashe          0.538905   2805
Kalista       0.535765   7932
Rek'Sai       0.535478   6543
Twisted Fate  0.534137   3990
Nidalee       0.533055   6128
Sivir         0.532408   6982
Brand         0.530857    929
Ahri          0.527424   5760
Hecarim       0.526680   4491
Singed        0.525773    816
Janna         0.525157  12045
Heimerdinger  0.523593    921
Blitzcrank    0.519726   6297
Soraka        0.519386   3724
Annie         0.517003   5838
Kog'Maw       0.516964   1737
Varus         0.516764   1156
Elise         0.515475   1499
Wukong        0.514355   1899
Irelia        0.514347   6274
Cassiopeia    0.514154   2452
Sion          0.511047   3192
Rumble        0.510583   3763
Fiddlesticks  0.510204   1725
Karthus       0.510134   1183
Jinx          0.509731   6967
Evelynn       0.509615   2332
Talon         0.508836   1670
...                ...    ...
Jarvan IV     0.479149   4550
Amumu         0.478836    905
Zilean        0.478142    350
Warwick       0.476676    327
Viktor        0.475976   3269
Azir          0.475402   2870
Rammus        0.475059    400
Tristana      0.475033   3577
Caitlyn       0.474093   3843
Master Yi     0.473758   1020
Cho'Gath      0.473671   1871
Ekko          0.471577   1991
Gnar          0.470955   3851
Zyra          0.470548    687
Syndra        0.470199    710
Ezreal        0.468677   5394
Dr. Mundo     0.466844    704
Renekton      0.466763   1608
Trundle       0.465640    393
Nocturne      0.460194    948
Tahm Kench    0.458594    659
Xin Zhao      0.458265    560
Zac           0.456368   1229
Quinn         0.455910    243
Shyvana       0.455232   1749
Galio         0.454389    264
Jax           0.454206   1215
Lucian        0.453410   5518
Lux           0.446937    817
Garen         0.431796    440

[126 rows x 2 columns]

In [ ]:
champion_roles_wins_losses = wins_losses.merge(champions).groupby(['name', 'role'])
champion_roles_wins_losses = champion_roles_wins_losses.agg({'win' : [np.mean, np.sum]})
champion_roles_wins_losses = champion_roles_wins_losses.sort(columns = [('win', 'mean')], ascending = False)
champion_roles_wins_losses

                           win
                          mean sum
name         role
Kog'Maw      support  1.000000   1
Nautilus     carry    1.000000   1
Lissandra    carry    1.000000   1
Miss Fortune support  1.000000   2
Shaco        carry    1.000000   1
Kassadin     carry    1.000000   1
Graves       support  1.000000   1
Soraka       carry    1.000000   1
Leona        carry    1.000000   1
Pantheon     carry    1.000000   3
Xin Zhao     carry    1.000000   2
Rumble       carry    1.000000   2
Katarina     carry    1.000000   1
Nunu         carry    1.000000   1
Vi           carry    1.000000   1
Kha'Zix      carry    1.000000   1
Lee Sin      carry    0.750000   3
Hecarim      carry    0.750000   3
Vel'Koz      carry    0.750000   3
Orianna      carry    0.750000   3
Skarner      support  0.750000   3
Sona         top      0.739130  17
Gnar         carry    0.714286   5
Xerath       carry    0.700000   7
Jayce        support  0.700000   7
Miss Fortune jungle   0.666667  12
Master Yi    carry    0.666667   2
Lux          top      0.666667   8
Trundle      mid      0.666667   4
Leona        mid      0.666667   2
...                        ...  ..
Nami         mid      0.200000   2
Taric        mid      0.200000   1
Ahri         carry    0.166667   1
Miss Fortune top      0.166667   1
Lux          jungle   0.157895   3
Swain        support  0.142857   1
Bard         top      0.100000   1
Lux          carry    0.000000   0
Sona         carry    0.000000   0
Viktor       carry    0.000000   0
Veigar       carry    0.000000   0
Warwick      support  0.000000   0
Zyra         carry    0.000000   0
Brand        carry    0.000000   0
Tahm Kench   mid      0.000000   0
Darius       carry    0.000000   0
Syndra       carry    0.000000   0
Draven       support  0.000000   0
Malzahar     carry    0.000000   0
Elise        carry    0.000000   0
Fiddlesticks carry    0.000000   0
Sion         carry    0.000000   0
Ryze         carry    0.000000   0
Renekton     carry    0.000000   0
Janna        carry    0.000000   0
Poppy        carry    0.000000   0
Olaf         carry    0.000000   0
Nocturne     carry    0.000000   0
Nami         carry    0.000000   0
Volibear     carry    0.000000   0

[593 rows x 2 columns]

# Task 3: Champion Synergies and Counters

Like with LoL King's [Top Lane Matchup](http://www.lolking.net/charts?region=all&type=top-matchup&range=weekly&map=sr&queue=1x1&league=ranked) and [Bottom Lane Synergy](http://www.lolking.net/charts?region=all&type=bottom-matchup&range=weekly&map=sr&queue=1x1&league=ranked), our goal is to help players compare their own choices with more successful choices.

    INSERT BALSAMIQ SCREENSHOTS HERE

# Conclusion

Our goal with is to use visualization techniques learned throughout the course in order to improve player choices. For now, this improvement will be based on visualizing the successes and failures of other players.